meu-bilhete/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "events#index"
  
  resources :events, only: [:index, :show]
  
  get 'checkout', to: 'events#checkout', as: 'checkout'
  
  resources :carts, only: [:show]


end

meu-bilhete/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

meu-bilhete/app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
end

meu-bilhete/app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :event
end

meu-bilhete/app/models/event.rb
class Event < ApplicationRecord
end

meu-bilhete/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one :cart

end

meu-bilhete/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    def after_sign_in_path_for(resource)
        if session[:event_id_for_checkout].present?
          finalize_purchase_path(session[:event_id_for_checkout]) 
        else
          root_path
        end
      end

      def after_sign_in_path_for(resource)
        if session[:event_id_for_checkout].present?
          event = Event.find(session[:event_id_for_checkout])
      
          # Encontre ou crie um carrinho para o usuário atual
          cart = current_user.cart || current_user.create_cart
      
          # Adicione o evento ao carrinho
          cart_item = cart.cart_items.find_or_initialize_by(event: event)
          cart_item.quantity = (cart_item.quantity || 0) + 1 # ou qualquer lógica para definir a quantidade
          cart_item.save!
      
          # Limpe a sessão
          session.delete(:event_id_for_checkout)
      
          cart_path(cart) # Substitua por sua rota para o carrinho de compras
        else
          root_path
        end
      end


end

meu-bilhete/app/controllers/carts_controller.rb
class CartsController < ApplicationController

    def show
        @cart = Cart.find(params[:id])
        @cart_items = @cart.cart_items.includes(:event)
      end


end

meu-bilhete/app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
      @events = Event.all
    end
    
    def show
        @event = Event.find(params[:id])
    end

    def checkout
        @event = Event.find(params[:event_id])
        session[:event_id_for_checkout] = @event.id
    end


end
  

meu-bilhete/app/helpers/application_helper.rb
module ApplicationHelper
end

meu-bilhete/app/helpers/carts_helper.rb
module CartsHelper
end

meu-bilhete/app/helpers/events_helper.rb
module EventsHelper
end

meu-bilhete/app/views/carts/show.html.erb
<h2>Seu Carrinho de Compras</h2>

<table>
  <thead>
    <tr>
      <th>Evento</th>
      <th>Quantidade</th>
      <th>Preço Total</th>
    </tr>
  </thead>
  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.event.name %></td>
        <td><%= cart_item.quantity %></td>
        <td><%= number_to_currency(cart_item.event.price * cart_item.quantity) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Finalizar Compra", checkout_path %>

meu-bilhete/app/views/events/checkout.html.erb
<h2>Finalizar Compra para <%= @event.name %></h2>

<p>Você já tem uma conta?</p>

<%= link_to "Sim, fazer login", new_user_session_path %>
<%= link_to "Não, criar conta", new_user_registration_path %>

meu-bilhete/app/views/events/index.html.erb
<h1>Eventos Disponíveis</h1>

<% @events.each do |event| %>
  <div class="event">
    <h2><%= event.name %></h2>
    <p><%= event.description %></p>
    <p>Data: <%= event.date.strftime('%d/%m/%Y %H:%M') %></p>
    <p>Preço: <%= number_to_currency(event.price) %></p>
    <%= link_to "Ver Detalhes", event_path(event), class: "details-button" %>
  </div>
<% end %>

meu-bilhete/app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p><%= @event.description %></p>
<p>Data: <%= @event.date.strftime('%d/%m/%Y %H:%M') %></p>
<p>Preço: <%= number_to_currency(@event.price) %></p>

<h2>Comprar Bilhetes</h2>
<%= form_with url: checkout_path, method: :get, local: true do %>
  <div>
    <label for="ticket_quantity">Quantidade:</label>
    <select name="ticket_quantity" id="ticket_quantity">
      <% (1..10).each do |number| %>
        <option value="<%= number %>"><%= number %></option>
      <% end %>
    </select>
  </div>
  <%= hidden_field_tag :event_id, @event.id %>
  <%= submit_tag "Comprar" %>
<% end %>

meu-bilhete/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeuBilhete</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>